plugins {
    id 'com.android.application'
}

android {
    compileSdk 34

    defaultConfig {
        minSdk 24
        targetSdk 34
        versionCode 17
        versionName "2.7.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

//        javaCompileOptions {
//            annotationProcessorOptions {
//                arguments["room.schemaLocation"] = "$projectDir/schemas"
//            }
//        }
    }
    signingConfigs {
        debug {
            storeFile file("${System.getenv("HOME")}/.android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
        release {
            def releaseStoreFile = System.getenv("RELEASE_STORE_FILE")
            def releaseStorePassword = System.getenv("RELEASE_STORE_PASSWORD")
            def releaseKeyAlias = System.getenv("RELEASE_KEY_ALIAS")
            def releaseKeyPassword = System.getenv("RELEASE_KEY_PASSWORD")
            if (releaseStoreFile != null) {
                storeFile file(releaseStoreFile)
            }
            if (releaseStorePassword != null) {
                storePassword releaseStorePassword
            }
            if (releaseKeyAlias != null) {
                keyAlias releaseKeyAlias
            }
            if (releaseKeyPassword != null) {
                keyPassword releaseKeyPassword
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            debuggable true
            signingConfig signingConfigs.debug
        }
    }

    flavorDimensions "environment"
    
    productFlavors {
        dev {
            dimension "environment"
            applicationId "com.vernu.sms.dev"
            versionNameSuffix "-dev"
            buildConfigField "String", "API_BASE_URL", '"https://api.dev.textbee.dev/api/v1/"'
            buildConfigField "String", "ENVIRONMENT", '"development"'
            resValue "string", "app_name", "textbee.dev (Dev)"
        }
        
        prod {
            dimension "environment"
            applicationId "com.vernu.sms"
            buildConfigField "String", "API_BASE_URL", '"https://api.textbee.dev/api/v1/"'
            buildConfigField "String", "ENVIRONMENT", '"production"'
            resValue "string", "app_name", "textbee.dev"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    implementation 'com.google.code.gson:gson:2.9.0'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.journeyapps:zxing-android-embedded:4.1.0'
    
    implementation 'androidx.work:work-runtime:2.7.1'
    implementation 'androidx.security:security-crypto:1.0.0'

//    def room_version = "2.4.2"
//    implementation "androidx.room:room-runtime:$room_version"
//    annotationProcessor "androidx.room:room-compiler:$room_version"
}
